name: Deploy
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - id: deploy
      uses: google-github-actions/deploy-appengine@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Use gcloud CLI
      run: |
        gcloud info